global:
  environment: staging
  domain: nuvorix.internal

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "nuvorix-sa"
  annotations: {}

secrets:
  existingSecret: ""

api:
  replicaCount: 2
  image:
    repository: ghcr.io/vnt1998/nuvorix-api
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  env:
    LOG_LEVEL: info
    AUTH_MODE: "development"
    AUTH_ENABLED: "true"
    PROMETHEUS_ENABLED: "true"
    MLFLOW_TRACKING_URI: ""
    OTEL_ENDPOINT: ""
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 80

web:
  replicaCount: 2
  image:
    repository: ghcr.io/vnt1998/nuvorix-web
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

database:
  type: postgresql
  url: ""
  postgresql:
    enabled: true
    host: postgresql.database
    port: 5432
    database: nuvorix
    username: nuvorix_user

redis:
  enabled: true
  url: "redis://redis-master:6379/0"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
  hosts:
    - host: console.nuvorix.internal
      paths:
        - path: /
          pathType: Prefix
          service: web
    - host: api.nuvorix.internal
      paths:
        - path: /
          pathType: Prefix
          service: api
  tls:
    - secretName: nuvorix-tls
      hosts:
        - console.nuvorix.internal
        - api.nuvorix.internal

monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s
    path: /metrics
